applications:
  app:
    type: 'php:8.2'
    dependencies:
      php:
        composer/composer: '^2'
    relationships:
      database: "db:mysql"
    hooks:
      build: |
        set -e
      deploy: |
        set -e
    web:
      locations:
        '/':
          root: "web"
          passthru: "/index.php"

services:
  db:
    type: mariadb:11.0

routes:
  "https://www.{default}/":
    type: upstream
    upstream: "app:http"
  "https://{default}/":
    type: redirect
    to: "https://www.{default}/"
